export {actions as paidmanagerActions, selector as paidmanagerSelector} from './paidmanager';
export {actions as coursesActions, selector as coursesSelector} from './courses';
export {actions as ordersActions, selector as ordersSelector} from './orders';
export {actions as schedulePaidAction, selector as schedulePaidSelector} from './schedule/paid';
export {actions as slotAction, selector as slotSelector} from './slot';
export {actions as studentActions, selector as studentSelector} from './student';
export {actions as teacherActions, selector as teacherSelector} from './teacher';
export {actions as demoClassActions, selector as demoClassSelector} from './demo-class';
export {actions as userActions, selector as userSelector} from './users';
export {actions as permissionActions, selector as permissionSelector} from './permission';
export {actions as curriculumActions, selector as curriculumSelector} from './curriculum';
export {actions as quizessActions, selector as quizessSelector} from './quizess';
export {actions as uploadiActions, selector as uploadSelector} from './upload';
export {actions as feedbackActions, selector as feedbackSelector} from './feedback';
export {actions as loaderboardActions, selector as loaderboardSelector} from './Loaderboard';
export {actions as socketdActions, selector as socketSelector} from './socket';
export { actions as gameActions, selector as gameSelector } from './game';
export {actions as playerResultActions, selector as playerResultSelector} from './playerResult';
export * from './store';
